[WIP] User can view the full article
CraftAcademy/D-pressed pull request #13
Opened 2018-08-16 07:57 UTC by ESteinman

## PT-link https://www.pivotaltracker.com/story/show/159731331

## User story:
```
As a visitor,
In order to read the full article,
I would like to be able to access the article page.
```

2018-08-16 14:54 UTC, Andycutter approved these changes
Reviewed
OK

2018-08-17 08:40 UTC, faraznaeem requested changes

2018-08-17 08:40 UTC, faraznaeem commented on features/user_can_view_the_full_article.feature
> +        Then I am on the 'This is so sad' page
Please use the same quotation marks for all the steps in the scenario

2018-08-17 08:40 UTC, faraznaeem commented on features/user_can_view_the_full_article.feature
> +        And I should see "2018-08-16"
Will the date pass today?

2018-08-17 09:54 UTC, faraznaeem approved these changes

2018-08-17 09:55 UTC, merged