Display ads on the landing page
CraftAcademy/D-pressed pull request #15
Opened 2018-08-16 16:15 UTC by Siianko

### PT story: ###
https://www.pivotaltracker.com/story/show/159733738
```
As an Editor,
In order to increase the revenue,
I would like to show advertising on the website. 
```

2018-08-17 08:43 UTC, faraznaeem requested changes

2018-08-17 08:43 UTC, faraznaeem commented on features/display_ads.feature
> +
Why is the Pt story here?

2018-08-17 08:43 UTC, faraznaeem commented on features/display_ads.feature
> +        Then I should see ad 'ad1'
Probably use another name than `ad1`

2018-08-20 11:20 UTC, ESteinman approved these changes

2018-08-21 08:42 UTC, Andycutter commented
<img width="1262" alt="screen shot 2018-08-21 at 10 40 11" src="https://user-images.githubusercontent.com/39304568/44390955-de369d80-a52e-11e8-87d7-5acd012128e3.png">

2018-08-21 12:59 UTC, merged