Language of the D-pressed
CraftAcademy/D-pressed pull request #28
Opened 2018-08-22 14:11 UTC by Siianko

### PT Story: 
https://www.pivotaltracker.com/story/show/159733230
```
As a user, 
In order to better understand the content on the web, 
I would like to have some language options. 
```

2018-08-22 18:59 UTC, Andycutter requested changes

2018-08-22 18:59 UTC, Andycutter commented on config/locales/se.yml
> +  Log_in: Logga in
log_in instead of Log_in ;-)

2018-08-22 18:59 UTC, Andycutter commented on config/locales/se.yml
> +  Sign_up: Signa upp mig
sign_up so everything is with small letters.
We need to change Sign_up to sign_up in the views though

2018-08-22 18:59 UTC, Andycutter commented on config/locales/se.yml
> +  Registration: Registrering
'registration' so everything is with small letters.
We need to change Registration to registration in the views though

2018-08-23 07:20 UTC, ESteinman commented on config/locales/se.yml
> +  Sign_up: Signa upp mig
Would name it;
"Kom ihåg mig" and "Registrera mig".

2018-08-24 13:29 UTC, tochman commented
Please fix merge conflicts and address the comments.

2018-08-24 19:08 UTC, merged